name:                gelatin-tutorial
version:             0.1.0.0
github:              "schell/gelatin-tutorial"
license:             BSD3
author:              "Schell Scivally"
maintainer:          "efsubenovex@gmail.com"
copyright:           "2018 Schell Scivally"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/schell/gelatin-tutorial#readme>

dependencies:
- base >= 4.7 && < 5
- gelatin-sdl2
- markdown-unlit
- mtl
- sdl2

executables: # chapters
  gelatin-tutorial-hello:
    main:                Main.lhs
    source-dirs:         src/Hello
    ghc-options:
    - -pgmL markdown-unlit
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  gelatin-tutorial-shapes:
    main:                Main.lhs
    source-dirs:         src/Shapes
    ghc-options:
    - -pgmL markdown-unlit
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N


tests:
  gelatin-tutorial-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
